name: Test/build

on:
  workflow_call: # Allows workflow to be invoked by other workflows
  pull_request:
    types: [opened, reopened, edited]
  push:
    branches: [main, "*print*"]

jobs:
  # Run tests before building (only once on Windows)
  test:
    runs-on: windows-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v1

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v1
        with:
          node-version: 22.12

      # Install dependencies (including dev dependencies)
      - name: Install dependencies
        run:
          npm ci # Ensures exact dependencies from package-lock.json



      #install playwright browsers onto build agent 

      - name: Install Playwright Browsers
        run: npx playwright install

      #Run actual tests
      - name: Run Playwright Tests
        run: npx playwright test
        env:
          NODE_ENV: test

      # Compile and run application
      - name: Build app
        run: npm run package
